### ISSUE TITLE
Submit collection for verification

### ISSUE THREAD

**Issue by giftedocean** [ethereum-avatar-service/eas-api-whitelist#1]
{
  "polygon": [
    {
      "contract": "0x7ad0b04f222fb7668c501fc2c2a98bb4eb9a1103",
      "name": "Four by GiftedOcean x Reddit Collectible Avatars",
      "author": "Gifted Ocean",
      "website": "https://www.reddit.com",
      "opensea": "https://opensea.io/collection/four-by-giftedocean-x-reddit-collectible-avatars"
    }
  ]
}

**Comment by giftedocean** [comment]
"polygon": [
{
"contract": "0x67a68aafa375bc4d2454eeb6e946a4dae027fd18",
"name": "Nori by GiftedOcean",
"author": "Gifted Ocean",
"website": "https://www.reddit.com",
"opensea": "https://opensea.io/collection/nori-by-giftedocean-x-reddit-collectible-avatars"

**Comment by giftedocean** [comment]
"polygon": [
{
"contract": "0x2d3d77a3da91b9032eb505dc4b1c9f7f29dc00aa",
"name": "Six by GiftedOcean x Reddit Collectible Avatars",
"author": "Gifted Ocean",
"website": "https://www.reddit.com",
"opensea": "https://opensea.io/collection/six-by-giftedocean-x-reddit-collectible-avatars"

**Comment by giftedocean** [comment]
"polygon": [
{
"contract": "0xad283a7d4d34300bf3f0336c79ab46325c866008",
"name": "Spooky Sequel: giftedocean x Reddit Collectible Avatars",
"author": "Gifted Ocean",
"website": "https://www.reddit.com",
"opensea": "https://opensea.io/collection/retro-reimagined-giftedocean-x-reddit-collectible"

**Comment by mickvandijke** [comment]
Thanks @giftedocean , your collections are now verified :)
